### Lägg till Monstera (P001)
POST http://127.0.0.1:8000/wishlist
Content-Type: application/json

{
    "userId": "user1",
    "productCode": "P001"
}

###

### Lägg till Strelitzia (P003)
POST http://127.0.0.1:8000/wishlist
Content-Type: application/json

{
    "userId": "user1",
    "productCode": "P003"
}

###

### Hämta listan - Här ser du nu namn, pris och bild-länkar!
GET http://127.0.0.1:8000/wishlist/user1

###

### Flytta Monstera till kundvagnen
POST http://127.0.0.1:8000/wishlist/user1/move-to-cart
Content-Type: application/json

{
    "productCode": "P001",
    "quantity": 1
}